import type {
  Control,
  ControlException,
  ControlTest,
} from "@/lib/domain/schema";
import { seedBase } from "./base";

/* ==================================================================
   Kiểm soát - 12 bản ghi
   ================================================================== */

export const SEED_CONTROLS: Control[] = [
  {
    ...seedBase("ctrl-01", "CTRL-2026-001"),
    name: "Sao lưu dữ liệu tự động hằng ngày và kiểm tra khôi phục",
    description:
      "Hệ thống tự động sao lưu toàn bộ dữ liệu nghiệp vụ mỗi ngày, hằng quý thực hiện diễn tập khôi phục.",
    riskIds: ["risk-01"],
    type: "Phòng ngừa",
    nature: "Tự động",
    frequency: "Hàng ngày",
    unitId: "unit-it",
    ownerId: "emp-tuan",
    processId: "prc-van-hanh",
    systemId: "sys-dc",
    isKeyControl: true,
    effectiveDate: "2025-07-01",
    expireDate: "",
    status: "Đang hiệu lực",
    statusNote: "",
    lastTestResult: "Hiệu quả một phần",
    lastTestDate: "2026-06-25",
    evidenceRequirement:
      "Nhật ký sao lưu hằng ngày, biên bản diễn tập khôi phục hằng quý.",
  },
  {
    ...seedBase("ctrl-02", "CTRL-2026-002"),
    name: "Giám sát tính sẵn sàng hệ thống 24/7 và cảnh báo tự động",
    description:
      "Công cụ giám sát theo dõi liên tục dịch vụ lõi, phát cảnh báo tới trực ca khi vượt ngưỡng.",
    riskIds: ["risk-01", "risk-08"],
    type: "Phát hiện",
    nature: "Tự động",
    frequency: "Liên tục",
    unitId: "unit-it",
    ownerId: "emp-yen",
    processId: "prc-van-hanh",
    systemId: "sys-dc",
    isKeyControl: true,
    effectiveDate: "2025-04-01",
    expireDate: "",
    status: "Đang hiệu lực",
    statusNote: "",
    lastTestResult: "Hiệu quả",
    lastTestDate: "2026-05-18",
    evidenceRequirement:
      "Báo cáo uptime hằng tháng, nhật ký cảnh báo và thời gian phản hồi.",
  },
  {
    ...seedBase("ctrl-03", "CTRL-2026-003"),
    name: "Rà soát định kỳ ma trận phân quyền truy cập dữ liệu",
    description:
      "Hằng quý rà soát toàn bộ tài khoản và quyền truy cập theo nguyên tắc quyền tối thiểu.",
    riskIds: ["risk-02", "risk-06"],
    type: "Phát hiện",
    nature: "Bán tự động",
    frequency: "Hàng quý",
    unitId: "unit-it",
    ownerId: "emp-tuan",
    processId: "prc-attt",
    systemId: "sys-crm",
    isKeyControl: true,
    effectiveDate: "2025-10-01",
    expireDate: "",
    status: "Đang hiệu lực",
    statusNote: "",
    lastTestResult: "Không hiệu quả",
    lastTestDate: "2026-04-20",
    evidenceRequirement:
      "Biên bản rà soát phân quyền, danh sách tài khoản bị thu hồi quyền.",
  },
  {
    ...seedBase("ctrl-04", "CTRL-2026-004"),
    name: "Mã hoá dữ liệu cá nhân khi lưu trữ và truyền nhận",
    description:
      "Áp dụng mã hoá cho toàn bộ trường dữ liệu cá nhân trong cơ sở dữ liệu và kênh truyền.",
    riskIds: ["risk-02", "risk-06"],
    type: "Phòng ngừa",
    nature: "Tự động",
    frequency: "Liên tục",
    unitId: "unit-it",
    ownerId: "emp-yen",
    processId: "prc-attt",
    systemId: "sys-crm",
    isKeyControl: true,
    effectiveDate: "2025-09-15",
    expireDate: "",
    status: "Đang hiệu lực",
    statusNote: "",
    lastTestResult: "Hiệu quả",
    lastTestDate: "2026-03-12",
    evidenceRequirement:
      "Cấu hình mã hoá, kết quả quét cấu hình bảo mật định kỳ.",
  },
  {
    ...seedBase("ctrl-05", "CTRL-2026-005"),
    name: "Phê duyệt hạn mức tín dụng trước khi ký hợp đồng",
    description:
      "Mọi hợp đồng bán chịu phải được chấm điểm tín dụng và phê duyệt hạn mức trước khi ký.",
    riskIds: ["risk-03"],
    type: "Phòng ngừa",
    nature: "Bán tự động",
    frequency: "Theo sự vụ",
    unitId: "unit-tc",
    ownerId: "emp-mai",
    processId: "prc-ban",
    systemId: "sys-erp",
    isKeyControl: true,
    effectiveDate: "2025-06-01",
    expireDate: "",
    status: "Đang hiệu lực",
    statusNote: "",
    lastTestResult: "Hiệu quả một phần",
    lastTestDate: "2026-05-30",
    evidenceRequirement:
      "Phiếu chấm điểm tín dụng, chứng từ phê duyệt hạn mức trên ERP.",
  },
  {
    ...seedBase("ctrl-06", "CTRL-2026-006"),
    name: "Đối chiếu công nợ và cảnh báo quá hạn hằng tuần",
    description:
      "Hệ thống tổng hợp tuổi nợ theo khách hàng, gửi cảnh báo tới đơn vị kinh doanh phụ trách.",
    riskIds: ["risk-03"],
    type: "Phát hiện",
    nature: "Tự động",
    frequency: "Hàng tuần",
    unitId: "unit-tc",
    ownerId: "emp-mai",
    processId: "prc-ban",
    systemId: "sys-erp",
    isKeyControl: false,
    effectiveDate: "2025-08-01",
    expireDate: "",
    status: "Đang hiệu lực",
    statusNote: "",
    lastTestResult: "Hiệu quả",
    lastTestDate: "2026-06-08",
    evidenceRequirement: "",
  },
  {
    ...seedBase("ctrl-07", "CTRL-2026-007"),
    name: "Đối chiếu ba chiều đơn mua - phiếu nhập - hoá đơn",
    description:
      "ERP tự động chặn thanh toán khi ba chứng từ không khớp về số lượng và giá trị.",
    riskIds: ["risk-07"],
    type: "Phòng ngừa",
    nature: "Tự động",
    frequency: "Theo sự vụ",
    unitId: "unit-tc",
    ownerId: "emp-mai",
    processId: "prc-mua",
    systemId: "sys-erp",
    isKeyControl: true,
    effectiveDate: "2025-05-01",
    expireDate: "",
    status: "Đang hiệu lực",
    statusNote: "",
    lastTestResult: "Hiệu quả",
    lastTestDate: "2026-04-05",
    evidenceRequirement:
      "Nhật ký chặn thanh toán, báo cáo chênh lệch ba chiều hằng tháng.",
  },
  {
    ...seedBase("ctrl-08", "CTRL-2026-008"),
    name: "Phân tách nhiệm vụ lập - duyệt - chi trong thanh toán",
    description:
      "Ba vai trò được cấu hình tách biệt trên hệ thống, một người không kiêm nhiệm hai vai.",
    riskIds: ["risk-07"],
    type: "Phòng ngừa",
    nature: "Bán tự động",
    frequency: "Theo sự vụ",
    unitId: "unit-tc",
    ownerId: "emp-mai",
    processId: "prc-mua",
    systemId: "sys-erp",
    isKeyControl: false,
    effectiveDate: "2025-05-01",
    expireDate: "",
    status: "Đang hiệu lực",
    statusNote: "",
    lastTestResult: "Hiệu quả",
    lastTestDate: "2026-04-05",
    evidenceRequirement: "",
  },
  {
    ...seedBase("ctrl-09", "CTRL-2026-009"),
    name: "Rà soát phạm vi phiên bản và chốt yêu cầu đầu chu kỳ",
    description:
      "Hội đồng sản phẩm chốt phạm vi trước mỗi chu kỳ phát hành, thay đổi giữa chu kỳ phải được phê duyệt.",
    riskIds: ["risk-04"],
    type: "Phòng ngừa",
    nature: "Thủ công",
    frequency: "Hàng tháng",
    unitId: "unit-sx",
    ownerId: "emp-binh",
    processId: "prc-pt",
    systemId: "",
    isKeyControl: false,
    effectiveDate: "2025-11-01",
    expireDate: "",
    status: "Đang hiệu lực",
    statusNote: "",
    lastTestResult: "Hiệu quả một phần",
    lastTestDate: "2026-06-15",
    evidenceRequirement: "",
  },
  {
    ...seedBase("ctrl-10", "CTRL-2026-010"),
    name: "Xây dựng và cập nhật bản đồ vị trí trọng yếu",
    description:
      "Nhân sự duy trì danh sách vị trí trọng yếu kèm người kế thừa dự kiến, cập nhật nửa năm một lần.",
    riskIds: ["risk-05"],
    type: "Phòng ngừa",
    nature: "Thủ công",
    frequency: "Hàng quý",
    unitId: "unit-ns",
    ownerId: "emp-anh",
    processId: "prc-ns",
    systemId: "",
    isKeyControl: false,
    effectiveDate: "2026-01-01",
    expireDate: "",
    status: "Đang hiệu lực",
    statusNote: "",
    lastTestResult: null,
    lastTestDate: "",
    evidenceRequirement: "",
  },
  {
    ...seedBase("ctrl-11", "CTRL-2026-011"),
    name: "Đánh giá tác động xử lý dữ liệu cá nhân trước khi triển khai",
    description:
      "Mọi tính năng mới có xử lý dữ liệu cá nhân phải hoàn thành hồ sơ đánh giá tác động trước khi phát hành.",
    riskIds: ["risk-06", "risk-02"],
    type: "Phòng ngừa",
    nature: "Thủ công",
    frequency: "Theo sự vụ",
    unitId: "unit-qtrr",
    ownerId: "emp-ha",
    processId: "prc-attt",
    systemId: "",
    isKeyControl: true,
    effectiveDate: "2026-03-01",
    expireDate: "",
    status: "Chờ duyệt",
    statusNote: "Đang chờ ban hành cùng quy chế bảo vệ dữ liệu cá nhân.",
    lastTestResult: null,
    lastTestDate: "",
    evidenceRequirement:
      "Hồ sơ đánh giá tác động, biên bản phê duyệt của Ban QTRR.",
  },
  {
    ...seedBase("ctrl-12", "CTRL-2026-012"),
    name: "Cam kết thời gian phản hồi hỗ trợ theo hạng khách hàng",
    description:
      "Hệ thống phân luồng yêu cầu theo hạng khách hàng và đo thời gian phản hồi thực tế.",
    riskIds: ["risk-09"],
    type: "Phát hiện",
    nature: "Bán tự động",
    frequency: "Hàng tuần",
    unitId: "unit-kd",
    ownerId: "emp-son",
    processId: "prc-ban",
    systemId: "sys-crm",
    isKeyControl: false,
    effectiveDate: "2026-02-01",
    expireDate: "",
    status: "Nháp",
    statusNote: "",
    lastTestResult: null,
    lastTestDate: "",
    evidenceRequirement: "",
  },
];

/* ==================================================================
   Kết quả kiểm tra kiểm soát - 8 bản ghi
   ================================================================== */

export const SEED_CONTROL_TESTS: ControlTest[] = [
  {
    ...seedBase("test-01", "TEST-2026-001"),
    controlId: "ctrl-01",
    period: "Quý II/2026",
    testDate: "2026-06-25",
    testerId: "emp-quang",
    method: "Kiểm tra chứng từ",
    sampleSize: 30,
    failCount: 4,
    result: "Hiệu quả một phần",
    finding:
      "4/30 ngày không có nhật ký xác nhận sao lưu thành công, chưa có biên bản diễn tập khôi phục quý II.",
    recommendation:
      "Bổ sung cảnh báo tự động khi sao lưu thất bại và lập lịch diễn tập khôi phục cố định.",
    deficiencyId: "def-01",
    evidenceNote: "Nhật ký sao lưu tháng 4 đến tháng 6 năm 2026.",
  },
  {
    ...seedBase("test-02", "TEST-2026-002"),
    controlId: "ctrl-02",
    period: "Quý II/2026",
    testDate: "2026-05-18",
    testerId: "emp-quang",
    method: "Quan sát",
    sampleSize: 20,
    failCount: 0,
    result: "Hiệu quả",
    finding: "",
    recommendation: "",
    deficiencyId: "",
    evidenceNote: "Báo cáo giám sát và nhật ký cảnh báo tháng 4, tháng 5.",
  },
  {
    ...seedBase("test-03", "TEST-2026-003"),
    controlId: "ctrl-03",
    period: "Quý I/2026",
    testDate: "2026-04-20",
    testerId: "emp-anh",
    method: "Phân tích dữ liệu",
    sampleSize: 120,
    failCount: 27,
    result: "Không hiệu quả",
    finding:
      "27 tài khoản đối tác vẫn còn quyền truy cập dữ liệu khách hàng sau khi kết thúc hợp đồng.",
    recommendation:
      "Thu hồi ngay các tài khoản tồn đọng, tự động hoá quy trình thu hồi quyền khi chấm dứt hợp đồng.",
    deficiencyId: "def-02",
    evidenceNote: "Bảng trích xuất danh sách tài khoản và quyền tại thời điểm rà soát.",
  },
  {
    ...seedBase("test-04", "TEST-2026-004"),
    controlId: "ctrl-04",
    period: "Quý I/2026",
    testDate: "2026-03-12",
    testerId: "emp-tuan",
    method: "Thực hiện lại",
    sampleSize: 15,
    failCount: 0,
    result: "Hiệu quả",
    finding: "",
    recommendation: "",
    deficiencyId: "",
    evidenceNote: "Kết quả quét cấu hình mã hoá trên môi trường vận hành.",
  },
  {
    ...seedBase("test-05", "TEST-2026-005"),
    controlId: "ctrl-05",
    period: "Quý II/2026",
    testDate: "2026-05-30",
    testerId: "emp-anh",
    method: "Kiểm tra chứng từ",
    sampleSize: 40,
    failCount: 6,
    result: "Hiệu quả một phần",
    finding:
      "6 hợp đồng được ký trước khi có phê duyệt hạn mức tín dụng, phê duyệt bổ sung sau ngày ký.",
    recommendation:
      "Chặn cứng trên hệ thống, không cho phát sinh hợp đồng khi chưa có hạn mức được duyệt.",
    deficiencyId: "def-03",
    evidenceNote: "Hồ sơ hợp đồng và phiếu phê duyệt hạn mức quý II.",
  },
  {
    ...seedBase("test-06", "TEST-2026-006"),
    controlId: "ctrl-06",
    period: "Quý II/2026",
    testDate: "2026-06-08",
    testerId: "emp-quang",
    method: "Phân tích dữ liệu",
    sampleSize: 12,
    failCount: 0,
    result: "Hiệu quả",
    finding: "",
    recommendation: "",
    deficiencyId: "",
    evidenceNote: "Báo cáo tuổi nợ và nhật ký gửi cảnh báo 12 tuần liên tiếp.",
  },
  {
    ...seedBase("test-07", "TEST-2026-007"),
    controlId: "ctrl-07",
    period: "Quý I/2026",
    testDate: "2026-04-05",
    testerId: "emp-anh",
    method: "Thực hiện lại",
    sampleSize: 25,
    failCount: 0,
    result: "Hiệu quả",
    finding: "",
    recommendation: "",
    deficiencyId: "",
    evidenceNote: "Thử nghiệm tạo chứng từ lệch giá trị, hệ thống chặn đúng thiết kế.",
  },
  {
    ...seedBase("test-08", "TEST-2026-008"),
    controlId: "ctrl-09",
    period: "Quý II/2026",
    testDate: "2026-06-15",
    testerId: "emp-quang",
    method: "Phỏng vấn",
    sampleSize: 8,
    failCount: 3,
    result: "Hiệu quả một phần",
    finding:
      "3/8 chu kỳ phát hành có thay đổi phạm vi giữa chu kỳ nhưng không có phê duyệt của hội đồng sản phẩm.",
    recommendation:
      "Bắt buộc ghi nhận yêu cầu thay đổi trên công cụ quản lý và gắn phê duyệt trước khi triển khai.",
    deficiencyId: "def-04",
    evidenceNote: "Biên bản họp hội đồng sản phẩm và lịch sử thay đổi phạm vi.",
  },
];

/* ==================================================================
   Ngoại lệ kiểm soát - 3 bản ghi
   ================================================================== */

export const SEED_CONTROL_EXCEPTIONS: ControlException[] = [
  {
    ...seedBase("exc-01", "EXC-2026-001"),
    controlId: "ctrl-03",
    reason:
      "Chưa thể rà soát phân quyền cho nhóm đối tác đại lý do đang trong giai đoạn chuyển đổi hệ thống CRM.",
    requesterId: "emp-tuan",
    approverId: "emp-ha",
    unitId: "unit-it",
    startDate: "2026-05-01",
    endDate: "2026-08-31",
    compensatingControl:
      "Giám sát nhật ký truy cập hằng tuần và giới hạn phạm vi dữ liệu đối tác được truy vấn.",
    residualRiskLevel: "Cao",
    status: "Đã duyệt",
    statusNote: "Phê duyệt kèm điều kiện báo cáo tiến độ hằng tháng.",
  },
  {
    ...seedBase("exc-02", "EXC-2026-002"),
    controlId: "ctrl-05",
    reason:
      "Nhóm khách hàng chiến lược cần ký hợp đồng gấp trong kỳ cao điểm, chưa kịp hoàn tất chấm điểm tín dụng.",
    requesterId: "emp-son",
    approverId: "",
    unitId: "unit-kd",
    startDate: "2026-07-01",
    endDate: "2026-09-30",
    compensatingControl:
      "Yêu cầu đặt cọc tối thiểu 30% giá trị hợp đồng và rà soát công nợ hằng tuần.",
    residualRiskLevel: "Trung bình",
    status: "Chờ duyệt",
    statusNote: "",
  },
  {
    ...seedBase("exc-03", "EXC-2026-003"),
    controlId: "ctrl-07",
    reason:
      "Một số nhà cung cấp nhỏ chưa xuất hoá đơn điện tử kịp thời, gây tắc nghẽn thanh toán.",
    requesterId: "emp-mai",
    approverId: "emp-ha",
    unitId: "unit-tc",
    startDate: "2026-01-15",
    endDate: "2026-04-15",
    compensatingControl:
      "Kế toán trưởng phê duyệt thủ công từng trường hợp kèm biên bản đối chiếu công nợ.",
    residualRiskLevel: "Trung bình",
    status: "Hết hiệu lực",
    statusNote: "Đã hết thời hạn ngoại lệ, kiểm soát quay lại vận hành bình thường.",
  },
];
