import type { GrcEvent } from "@/lib/domain/schema";
import { seedBase } from "./base";

/* ==================================================================
   Sự kiện - 10 bản ghi
   ------------------------------------------------------------------
   - evt-02 : nguồn phát sinh của điểm yếu def-05 và hai hành động
              kppn-05, kppn-06
   - evt-04 : nguồn phát sinh của hành động kppn-10
   - evt-03 : sự kiện suýt xảy ra (near miss), không có tổn thất thực tế
   - evt-07 : sau xác minh kết luận không phải sự kiện -> huỷ ghi nhận
   Phủ đủ 7 trạng thái trong EVENT_FLOW.
   ================================================================== */

export const SEED_EVENTS: GrcEvent[] = [
  {
    ...seedBase("evt-01", "EVT-2026-001"),
    name: "Gián đoạn dịch vụ 92 phút do sự cố nguồn điện trung tâm dữ liệu",
    description:
      "Cụm thiết bị nguồn tại trung tâm dữ liệu chính gặp sự cố, hệ thống chuyển sang nguồn dự phòng chậm khiến dịch vụ khách hàng gián đoạn 92 phút trong giờ cao điểm.",
    categoryId: "cat-sk-vh",
    unitId: "unit-it",
    occurredDate: "2026-02-18",
    detectedDate: "2026-02-18",
    reporterId: "emp-tuan",
    handlerId: "emp-yen",
    impactTypes: ["Vận hành", "Uy tín"],
    severity: "Cao",
    isNearMiss: false,
    isConfidential: false,
    estimatedLoss: 250000000,
    actualLoss: 180000000,
    recoveredAmount: null,
    relatedRiskIds: ["risk-01"],
    relatedControlIds: ["ctrl-02"],
    deficiencyIds: [],
    kppnIds: ["kppn-09"],
    rootCause:
      "Cụm thiết bị nguồn đã hết vòng đời khuyến nghị của nhà sản xuất, đồng thời cơ chế chuyển nguồn dự phòng chưa được diễn tập trong 12 tháng gần nhất nên thời gian chuyển đổi vượt xa thiết kế.",
    lessonLearned:
      "Cần đưa diễn tập chuyển nguồn vào lịch định kỳ và lập kế hoạch thay thế thiết bị theo vòng đời thay vì chờ hỏng mới xử lý.",
    status: "Đã đóng",
    statusNote:
      "Đóng ngày 30/04/2026 sau khi hoàn tất phân tích nguyên nhân và phê duyệt kế hoạch thay thế thiết bị.",
  },
  {
    ...seedBase("evt-02", "EVT-2026-002"),
    name: "Rò rỉ dữ liệu khách hàng qua tài khoản đối tác đại lý",
    description:
      "Một tài khoản đối tác đại lý đã chấm dứt hợp đồng vẫn truy cập và tải về dữ liệu của 4.200 khách hàng. Sự việc được phát hiện sau khi khách hàng phản ánh bị tiếp thị bởi bên thứ ba.",
    categoryId: "cat-sk-attt",
    unitId: "unit-it",
    occurredDate: "2026-03-10",
    detectedDate: "2026-03-15",
    reporterId: "emp-son",
    handlerId: "emp-yen",
    impactTypes: ["An toàn thông tin", "Pháp lý", "Uy tín"],
    severity: "Trọng yếu",
    isNearMiss: false,
    isConfidential: true,
    estimatedLoss: 3200000000,
    actualLoss: 850000000,
    recoveredAmount: null,
    relatedRiskIds: ["risk-02", "risk-06"],
    relatedControlIds: ["ctrl-03", "ctrl-04"],
    deficiencyIds: ["def-05"],
    kppnIds: ["kppn-05", "kppn-06"],
    rootCause:
      "Tài khoản đối tác không được thu hồi quyền khi hợp đồng kết thúc, đồng thời hệ thống CRM chưa có luật phát hiện hành vi truy vấn khối lượng lớn bất thường nên sự việc kéo dài nhiều ngày mà không bị chặn.",
    lessonLearned: "",
    status: "Đang xử lý",
    statusNote:
      "Đã hoàn tất điều tra, đang triển khai hai hành động khắc phục và phòng ngừa liên quan.",
  },
  {
    ...seedBase("evt-03", "EVT-2026-003"),
    name: "Suýt mất dữ liệu do cấu hình sao lưu sai vùng lưu trữ",
    description:
      "Kỹ sư vận hành phát hiện tác vụ sao lưu của một cụm cơ sở dữ liệu trỏ sai vùng lưu trữ đã ngừng sử dụng. Sự việc được phát hiện trước khi phát sinh yêu cầu khôi phục nên chưa gây hậu quả.",
    categoryId: "cat-sk-vh",
    unitId: "unit-it",
    occurredDate: "2026-06-20",
    detectedDate: "2026-06-22",
    reporterId: "emp-tuan",
    handlerId: "emp-yen",
    impactTypes: ["Vận hành"],
    severity: "Trung bình",
    isNearMiss: true,
    isConfidential: false,
    estimatedLoss: 900000000,
    actualLoss: null,
    recoveredAmount: null,
    relatedRiskIds: ["risk-01"],
    relatedControlIds: ["ctrl-01"],
    deficiencyIds: ["def-01"],
    kppnIds: ["kppn-01"],
    rootCause: "",
    lessonLearned: "",
    status: "Đã xác minh",
    statusNote:
      "Đã xác nhận là sự kiện suýt xảy ra, chuyển thông tin bổ sung cho điểm yếu DEF-2026-001.",
  },
  {
    ...seedBase("evt-04", "EVT-2026-004"),
    name: "Thanh toán trùng cho nhà cung cấp dịch vụ hạ tầng",
    description:
      "Một hoá đơn dịch vụ hạ tầng được thanh toán hai lần trong cùng kỳ do tạo hai đề nghị thanh toán từ hai bộ chứng từ khác nhau.",
    categoryId: "cat-sk-tc",
    unitId: "unit-tc",
    occurredDate: "2026-08-03",
    detectedDate: "2026-08-10",
    reporterId: "emp-mai",
    handlerId: "emp-anh",
    impactTypes: ["Tài chính"],
    severity: "Cao",
    isNearMiss: false,
    isConfidential: false,
    estimatedLoss: 420000000,
    actualLoss: 420000000,
    recoveredAmount: 0,
    relatedRiskIds: ["risk-07"],
    relatedControlIds: ["ctrl-07", "ctrl-08"],
    deficiencyIds: [],
    kppnIds: ["kppn-10"],
    rootCause: "",
    lessonLearned: "",
    status: "Đang điều tra",
    statusNote:
      "Đang đối chiếu toàn bộ giao dịch với nhà cung cấp trong 6 tháng gần nhất.",
  },
  {
    ...seedBase("evt-05", "EVT-2026-005"),
    name: "Khiếu nại của khách hàng về thời gian phản hồi hỗ trợ ca tối",
    description:
      "Nhóm khách hàng doanh nghiệp phản ánh yêu cầu hỗ trợ gửi sau 18h thường chỉ được phản hồi vào sáng hôm sau, vượt cam kết dịch vụ đã ký.",
    categoryId: "cat-sk-kh",
    unitId: "unit-kd",
    occurredDate: "2026-08-08",
    detectedDate: "2026-08-11",
    reporterId: "emp-linh",
    handlerId: "",
    impactTypes: ["Uy tín"],
    severity: "Trung bình",
    isNearMiss: false,
    isConfidential: false,
    estimatedLoss: 120000000,
    actualLoss: null,
    recoveredAmount: null,
    relatedRiskIds: ["risk-09"],
    relatedControlIds: ["ctrl-12"],
    deficiencyIds: [],
    kppnIds: [],
    rootCause: "",
    lessonLearned: "",
    status: "Mới ghi nhận",
    statusNote: "",
  },
  {
    ...seedBase("evt-06", "EVT-2026-006"),
    name: "Phát hiện chuỗi thử đăng nhập bất thường vào cổng quản trị",
    description:
      "Hệ thống ghi nhận hơn 4.000 lượt thử đăng nhập thất bại vào cổng quản trị nội bộ từ dải địa chỉ nước ngoài trong vòng 3 giờ.",
    categoryId: "cat-sk-attt",
    unitId: "unit-it",
    occurredDate: "2026-08-12",
    detectedDate: "2026-08-12",
    reporterId: "emp-tuan",
    handlerId: "emp-yen",
    impactTypes: ["An toàn thông tin"],
    severity: "Cao",
    isNearMiss: false,
    isConfidential: true,
    estimatedLoss: 600000000,
    actualLoss: null,
    recoveredAmount: null,
    relatedRiskIds: ["risk-02"],
    relatedControlIds: ["ctrl-04"],
    deficiencyIds: [],
    kppnIds: [],
    rootCause: "",
    lessonLearned: "",
    status: "Đang xác minh",
    statusNote:
      "Đã chặn tạm dải địa chỉ nghi ngờ, đang xác minh có tài khoản nào bị xâm nhập thành công hay không.",
  },
  {
    ...seedBase("evt-07", "EVT-2026-007"),
    name: "Nghi ngờ lộ thông tin bảng lương nội bộ",
    description:
      "Có phản ánh về việc thông tin thu nhập của một nhóm nhân sự bị chia sẻ ngoài phạm vi cho phép.",
    categoryId: "cat-sk-attt",
    unitId: "unit-ns",
    occurredDate: "2026-05-04",
    detectedDate: "2026-05-06",
    reporterId: "emp-linh",
    handlerId: "emp-anh",
    impactTypes: ["Con người"],
    severity: "Thấp",
    isNearMiss: false,
    isConfidential: true,
    estimatedLoss: null,
    actualLoss: null,
    recoveredAmount: null,
    relatedRiskIds: [],
    relatedControlIds: [],
    deficiencyIds: [],
    kppnIds: [],
    rootCause: "",
    lessonLearned: "",
    status: "Huỷ ghi nhận",
    statusNote:
      "Kết quả xác minh cho thấy thông tin được trao đổi trong phạm vi được phân quyền, không phải sự kiện rủi ro.",
  },
  {
    ...seedBase("evt-08", "EVT-2026-008"),
    name: "Sai số liệu công nợ trên báo cáo gửi khách hàng doanh nghiệp",
    description:
      "Báo cáo đối chiếu công nợ quý I gửi 38 khách hàng có số dư sai do lấy dữ liệu trước khi hoàn tất bút toán điều chỉnh cuối kỳ.",
    categoryId: "cat-sk-tc",
    unitId: "unit-tc",
    occurredDate: "2026-04-06",
    detectedDate: "2026-04-09",
    reporterId: "emp-mai",
    handlerId: "emp-anh",
    impactTypes: ["Tài chính", "Uy tín"],
    severity: "Trung bình",
    isNearMiss: false,
    isConfidential: false,
    estimatedLoss: 90000000,
    actualLoss: 65000000,
    recoveredAmount: 65000000,
    relatedRiskIds: ["risk-03"],
    relatedControlIds: ["ctrl-06"],
    deficiencyIds: [],
    kppnIds: [],
    rootCause:
      "Lịch xuất báo cáo đối chiếu được đặt trước thời điểm khoá sổ điều chỉnh cuối kỳ, đồng thời không có bước kiểm tra chéo số liệu trước khi gửi ra bên ngoài.",
    lessonLearned:
      "Mọi báo cáo gửi khách hàng phải được xuất sau khi khoá sổ và có bước soát xét của kế toán tổng hợp.",
    status: "Đã đóng",
    statusNote:
      "Đã gửi báo cáo đính chính tới toàn bộ khách hàng bị ảnh hưởng, đóng sự kiện ngày 25/04/2026.",
  },
  {
    ...seedBase("evt-09", "EVT-2026-009"),
    name: "Chậm phát hành bản cập nhật do lỗi môi trường triển khai",
    description:
      "Bản cập nhật định kỳ bị lùi 5 ngày so với kế hoạch do môi trường triển khai không đồng bộ cấu hình với môi trường kiểm thử.",
    categoryId: "cat-sk-vh",
    unitId: "unit-sx",
    occurredDate: "2026-08-05",
    detectedDate: "2026-08-06",
    reporterId: "emp-binh",
    handlerId: "",
    impactTypes: ["Vận hành"],
    severity: "Trung bình",
    isNearMiss: false,
    isConfidential: false,
    estimatedLoss: 150000000,
    actualLoss: null,
    recoveredAmount: null,
    relatedRiskIds: ["risk-04"],
    relatedControlIds: ["ctrl-09"],
    deficiencyIds: ["def-04"],
    kppnIds: [],
    rootCause: "",
    lessonLearned: "",
    status: "Mới ghi nhận",
    statusNote: "",
  },
  {
    ...seedBase("evt-10", "EVT-2026-010"),
    name: "Mất kết nối tới nhà cung cấp dịch vụ đám mây trong 45 phút",
    description:
      "Nhà cung cấp đám mây gặp sự cố tại vùng dịch vụ đang sử dụng, khiến một phần tính năng của khách hàng không khả dụng trong 45 phút.",
    categoryId: "cat-sk-vh",
    unitId: "unit-it",
    occurredDate: "2026-07-22",
    detectedDate: "2026-07-22",
    reporterId: "emp-tuan",
    handlerId: "emp-yen",
    impactTypes: ["Vận hành", "Uy tín"],
    severity: "Cao",
    isNearMiss: false,
    isConfidential: false,
    estimatedLoss: 300000000,
    actualLoss: 110000000,
    recoveredAmount: 40000000,
    relatedRiskIds: ["risk-08", "risk-01"],
    relatedControlIds: ["ctrl-02"],
    deficiencyIds: [],
    kppnIds: [],
    rootCause:
      "Toàn bộ dịch vụ đặt tại một vùng của một nhà cung cấp duy nhất, chưa có phương án triển khai đa vùng nên không thể chuyển hướng lưu lượng khi nhà cung cấp gặp sự cố.",
    lessonLearned: "",
    status: "Đang xử lý",
    statusNote:
      "Đang đàm phán bồi thường theo cam kết mức dịch vụ và đánh giá phương án triển khai đa vùng.",
  },
];
