import type { Kppn } from "@/lib/domain/schema";
import { seedBase } from "./base";

/* ==================================================================
   Hành động khắc phục & phòng ngừa (KPPN) - 12 bản ghi
   ------------------------------------------------------------------
   Nguyên tắc nghiệp vụ: GRC chỉ điều phối, việc thực thi nằm ở hệ
   thống nguồn.
   - Bộ phận chung        -> AMIS Công việc
   - Khối IT / Sản xuất   -> JIRA
   - Nội bộ ban QTRR      -> Theo dõi trong GRC

   Mốc so sánh quá hạn: ngày hiện tại 16/08/2026.
   Các hành động quá hạn: kppn-02, kppn-04, kppn-11.
   ================================================================== */

export const SEED_KPPNS: Kppn[] = [
  {
    ...seedBase("kppn-01", "KPPN-2026-001"),
    name: "Tích hợp cảnh báo sao lưu thất bại vào hệ thống giám sát tập trung",
    description:
      "Đẩy nhật ký của công cụ sao lưu về hệ thống giám sát tập trung, cấu hình luật cảnh báo tới nhóm trực ca ngay khi một tác vụ sao lưu thất bại.",
    type: "Khắc phục",
    deficiencyId: "def-01",
    riskId: "risk-01",
    eventId: "",
    unitId: "unit-it",
    assigneeId: "emp-tuan",
    supervisorId: "emp-yen",
    executionSystem: "JIRA",
    externalTaskCode: "ITOPS-2451",
    externalUrl: "https://jira.misa.com.vn/browse/ITOPS-2451",
    lastSyncedAt: "2026-08-14T03:15:00.000Z",
    startDate: "2026-07-01",
    dueDate: "2026-08-31",
    completedDate: "",
    progress: 60,
    status: "Đang thực hiện",
    statusNote: "",
    result: "",
    evidenceNote: "",
    estimatedCost: 45000000,
  },
  {
    ...seedBase("kppn-02", "KPPN-2026-002"),
    name: "Đưa diễn tập khôi phục dữ liệu vào lịch công việc định kỳ hằng quý",
    description:
      "Ban hành lịch diễn tập khôi phục cố định theo quý, phân công người chủ trì và mẫu biên bản diễn tập chuẩn.",
    type: "Phòng ngừa",
    deficiencyId: "def-01",
    riskId: "risk-01",
    eventId: "",
    unitId: "unit-it",
    assigneeId: "emp-tuan",
    supervisorId: "emp-yen",
    executionSystem: "AMIS Công việc",
    externalTaskCode: "CV-2026-08812",
    externalUrl: "https://amisapp.misa.vn/task/CV-2026-08812",
    lastSyncedAt: "2026-08-15T01:30:00.000Z",
    startDate: "2026-07-01",
    dueDate: "2026-07-31",
    completedDate: "",
    progress: 40,
    status: "Đang thực hiện",
    statusNote:
      "Đã quá hạn, đang chờ Trung tâm CNTT bố trí khung giờ diễn tập ngoài giờ cao điểm.",
    result: "",
    evidenceNote: "",
    estimatedCost: 12000000,
  },
  {
    ...seedBase("kppn-03", "KPPN-2026-003"),
    name: "Thu hồi ngay quyền truy cập của 27 tài khoản đối tác tồn đọng",
    description:
      "Rà soát danh sách tài khoản đối tác đã chấm dứt hợp đồng, thu hồi toàn bộ quyền truy cập dữ liệu khách hàng và lập biên bản xác nhận.",
    type: "Khắc phục",
    deficiencyId: "def-02",
    riskId: "risk-02",
    eventId: "",
    unitId: "unit-it",
    assigneeId: "emp-tuan",
    supervisorId: "emp-yen",
    executionSystem: "AMIS Công việc",
    externalTaskCode: "CV-2026-07104",
    externalUrl: "https://amisapp.misa.vn/task/CV-2026-07104",
    lastSyncedAt: "2026-05-11T02:00:00.000Z",
    startDate: "2026-04-21",
    dueDate: "2026-05-15",
    completedDate: "2026-05-10",
    progress: 100,
    status: "Hoàn thành",
    statusNote: "",
    result:
      "Đã thu hồi toàn bộ 27 tài khoản, trong đó 21 tài khoản bị vô hiệu hoá và 6 tài khoản được giới hạn lại phạm vi dữ liệu theo hợp đồng mới.",
    evidenceNote:
      "Biên bản thu hồi quyền ngày 10/05/2026, ảnh chụp trạng thái tài khoản sau khi xử lý.",
    estimatedCost: 0,
  },
  {
    ...seedBase("kppn-04", "KPPN-2026-004"),
    name: "Tự động thu hồi quyền truy cập khi chấm dứt hợp đồng đối tác",
    description:
      "Bổ sung bước bắt buộc trong quy trình chấm dứt hợp đồng: hệ thống hợp đồng gửi tín hiệu sang quản trị người dùng để tự động vô hiệu hoá tài khoản liên quan.",
    type: "Phòng ngừa",
    deficiencyId: "def-02",
    riskId: "risk-02",
    eventId: "",
    unitId: "unit-it",
    assigneeId: "emp-yen",
    supervisorId: "emp-ha",
    executionSystem: "JIRA",
    externalTaskCode: "SEC-1187",
    externalUrl: "https://jira.misa.com.vn/browse/SEC-1187",
    lastSyncedAt: "2026-08-15T01:30:00.000Z",
    startDate: "2026-05-05",
    dueDate: "2026-07-15",
    completedDate: "",
    progress: 55,
    status: "Đang thực hiện",
    statusNote:
      "Đã quá hạn, phần tích hợp phụ thuộc lịch nâng cấp hệ thống CRM dự kiến cuối tháng 8.",
    result: "",
    evidenceNote: "",
    estimatedCost: 180000000,
  },
  {
    ...seedBase("kppn-05", "KPPN-2026-005"),
    name: "Bổ sung luật phát hiện truy vấn dữ liệu bất thường trên CRM",
    description:
      "Xây dựng bộ luật phát hiện hành vi bất thường: truy vấn khối lượng lớn, truy cập ngoài giờ làm việc, tải dữ liệu vượt ngưỡng cho phép.",
    type: "Khắc phục",
    deficiencyId: "def-05",
    riskId: "risk-02",
    eventId: "evt-02",
    unitId: "unit-it",
    assigneeId: "emp-tuan",
    supervisorId: "emp-yen",
    executionSystem: "JIRA",
    externalTaskCode: "SEC-1204",
    externalUrl: "https://jira.misa.com.vn/browse/SEC-1204",
    lastSyncedAt: "2026-08-15T01:30:00.000Z",
    startDate: "2026-04-01",
    dueDate: "2026-08-20",
    completedDate: "",
    progress: 100,
    status: "Chờ nghiệm thu",
    statusNote: "Đã bật luật cảnh báo trên môi trường vận hành, chờ Ban QTRR nghiệm thu.",
    result: "",
    evidenceNote: "",
    estimatedCost: 95000000,
  },
  {
    ...seedBase("kppn-06", "KPPN-2026-006"),
    name: "Đẩy toàn bộ nhật ký truy cập CRM về công cụ giám sát tập trung",
    description:
      "Chuẩn hoá định dạng nhật ký truy cập và thiết lập luồng thu thập tập trung để phục vụ phân tích, truy vết và điều tra sự kiện.",
    type: "Phòng ngừa",
    deficiencyId: "def-05",
    riskId: "risk-02",
    eventId: "evt-02",
    unitId: "unit-it",
    assigneeId: "emp-yen",
    supervisorId: "emp-ha",
    executionSystem: "Theo dõi trong GRC",
    externalTaskCode: "",
    externalUrl: "",
    lastSyncedAt: "",
    startDate: "2026-08-20",
    dueDate: "2026-11-30",
    completedDate: "",
    progress: 0,
    status: "Chưa bắt đầu",
    statusNote: "",
    result: "",
    evidenceNote: "",
    estimatedCost: 130000000,
  },
  {
    ...seedBase("kppn-07", "KPPN-2026-007"),
    name: "Thu hồi quyền xung đột và bật kiểm tra phân tách nhiệm vụ trên ERP",
    description:
      "Thu hồi quyền của 2 tài khoản bị gán đồng thời quyền lập và duyệt đề nghị thanh toán, đồng thời bật chức năng cảnh báo xung đột quyền tự động.",
    type: "Khắc phục",
    deficiencyId: "def-06",
    riskId: "risk-07",
    eventId: "",
    unitId: "unit-tc",
    assigneeId: "emp-mai",
    supervisorId: "emp-anh",
    executionSystem: "AMIS Công việc",
    externalTaskCode: "CV-2026-05930",
    externalUrl: "https://amisapp.misa.vn/task/CV-2026-05930",
    lastSyncedAt: "2026-06-21T02:00:00.000Z",
    startDate: "2026-03-10",
    dueDate: "2026-06-30",
    completedDate: "2026-06-20",
    progress: 100,
    status: "Hoàn thành",
    statusNote: "",
    result:
      "Đã thu hồi quyền của 2 tài khoản, bật quy tắc kiểm tra xung đột quyền chạy hằng đêm và gửi báo cáo cho Kế toán trưởng.",
    evidenceNote:
      "Ảnh chụp cấu hình quy tắc xung đột quyền, báo cáo kiểm tra 3 kỳ liên tiếp không phát hiện vi phạm.",
    estimatedCost: 25000000,
  },
  {
    ...seedBase("kppn-08", "KPPN-2026-008"),
    name: "Chặn cứng việc tạo hợp đồng bán chịu khi chưa duyệt hạn mức tín dụng",
    description:
      "Cấu hình ERP không cho phép lưu hợp đồng bán chịu nếu khách hàng chưa có hạn mức tín dụng còn hiệu lực được phê duyệt.",
    type: "Phòng ngừa",
    deficiencyId: "",
    riskId: "risk-03",
    eventId: "",
    unitId: "unit-tc",
    assigneeId: "emp-mai",
    supervisorId: "emp-ha",
    executionSystem: "JIRA",
    externalTaskCode: "",
    externalUrl: "",
    lastSyncedAt: "",
    startDate: "2026-09-01",
    dueDate: "2026-11-15",
    completedDate: "",
    progress: 0,
    status: "Chờ duyệt",
    statusNote: "Đang chờ Ban QTRR phê duyệt trước khi giao việc sang JIRA.",
    result: "",
    evidenceNote: "",
    estimatedCost: 60000000,
  },
  {
    ...seedBase("kppn-09", "KPPN-2026-009"),
    name: "Thay thế thiết bị nguồn hết vòng đời tại trung tâm dữ liệu chính",
    description:
      "Mua sắm và thay thế cụm thiết bị nguồn đã hết vòng đời, bổ sung nguồn dự phòng theo mô hình song song.",
    type: "Phòng ngừa",
    deficiencyId: "",
    riskId: "risk-01",
    eventId: "",
    unitId: "unit-it",
    assigneeId: "emp-yen",
    supervisorId: "emp-ceo",
    executionSystem: "AMIS Công việc",
    externalTaskCode: "CV-2026-09015",
    externalUrl: "https://amisapp.misa.vn/task/CV-2026-09015",
    lastSyncedAt: "2026-08-15T01:30:00.000Z",
    startDate: "2026-06-15",
    dueDate: "2026-10-31",
    completedDate: "",
    progress: 35,
    status: "Đang thực hiện",
    statusNote: "",
    result: "",
    evidenceNote: "",
    estimatedCost: 1850000000,
  },
  {
    ...seedBase("kppn-10", "KPPN-2026-010"),
    name: "Thu hồi khoản thanh toán trùng cho nhà cung cấp",
    description:
      "Làm việc với nhà cung cấp để đối trừ hoặc hoàn trả khoản thanh toán trùng, đồng thời rà soát các giao dịch tương tự trong 6 tháng gần nhất.",
    type: "Khắc phục",
    deficiencyId: "",
    riskId: "risk-07",
    eventId: "evt-04",
    unitId: "unit-tc",
    assigneeId: "emp-mai",
    supervisorId: "emp-anh",
    executionSystem: "AMIS Công việc",
    externalTaskCode: "",
    externalUrl: "",
    lastSyncedAt: "",
    startDate: "2026-08-18",
    dueDate: "2026-09-30",
    completedDate: "",
    progress: 0,
    status: "Nháp",
    statusNote: "",
    result: "",
    evidenceNote: "",
    estimatedCost: 0,
  },
  {
    ...seedBase("kppn-11", "KPPN-2026-011"),
    name: "Lập danh mục hoạt động xử lý dữ liệu cá nhân toàn công ty",
    description:
      "Rà soát toàn bộ điểm thu thập dữ liệu cá nhân, xác định cơ sở pháp lý và lập hồ sơ đánh giá tác động theo quy định hiện hành.",
    type: "Phòng ngừa",
    deficiencyId: "",
    riskId: "risk-06",
    eventId: "",
    unitId: "unit-qtrr",
    assigneeId: "emp-quang",
    supervisorId: "emp-ha",
    executionSystem: "Theo dõi trong GRC",
    externalTaskCode: "",
    externalUrl: "",
    lastSyncedAt: "",
    startDate: "2026-03-01",
    dueDate: "2026-06-30",
    completedDate: "",
    progress: 45,
    status: "Đang thực hiện",
    statusNote:
      "Đã quá hạn, mới hoàn thành rà soát 4/9 khối đơn vị do thiếu nhân sự phối hợp.",
    result: "",
    evidenceNote: "",
    estimatedCost: 0,
  },
  {
    ...seedBase("kppn-12", "KPPN-2026-012"),
    name: "Tuyển bổ sung nhân sự hỗ trợ khách hàng ca tối",
    description:
      "Bổ sung 5 nhân sự trực ca tối nhằm rút ngắn thời gian phản hồi yêu cầu hỗ trợ của khách hàng hạng ưu tiên.",
    type: "Khắc phục",
    deficiencyId: "",
    riskId: "risk-09",
    eventId: "",
    unitId: "unit-kd",
    assigneeId: "emp-son",
    supervisorId: "emp-anh",
    executionSystem: "AMIS Công việc",
    externalTaskCode: "",
    externalUrl: "",
    lastSyncedAt: "",
    startDate: "2026-04-01",
    dueDate: "2026-07-31",
    completedDate: "",
    progress: 20,
    status: "Huỷ",
    statusNote:
      "Huỷ theo chỉ đạo tại cuộc họp ngày 05/06/2026, chuyển sang phương án thuê ngoài dịch vụ hỗ trợ ca tối.",
    result: "",
    evidenceNote: "",
    estimatedCost: 420000000,
  },
];
