import type { Risk } from "@/lib/domain/schema";
import { seedBase } from "./base";

export const SEED_RISKS: Risk[] = [
  {
    ...seedBase("risk-01", "RISK-2026-001"),
    name: "Gián đoạn dịch vụ do sự cố trung tâm dữ liệu",
    description:
      "Hạ tầng trung tâm dữ liệu chính gặp sự cố khiến dịch vụ khách hàng bị gián đoạn diện rộng.",
    cause:
      "Thiết bị nguồn hết vòng đời, phương án dự phòng chưa được diễn tập đầy đủ.",
    consequence:
      "Khách hàng không truy cập được dịch vụ, ảnh hưởng uy tín và doanh thu định kỳ.",
    categoryId: "cat-cntt",
    objectiveIds: ["obj-04", "obj-02"],
    unitId: "unit-it",
    ownerId: "emp-yen",
    processId: "prc-van-hanh",
    systemId: "sys-dc",
    source: "Nội bộ",
    inherentLikelihood: 4,
    inherentImpact: 5,
    residualLikelihood: 3,
    residualImpact: 4,
    treatment: "Giảm thiểu",
    treatmentNote:
      "Đầu tư hạ tầng dự phòng, diễn tập chuyển đổi dự phòng định kỳ 6 tháng một lần.",
    isZeroTolerance: true,
    isKeyRisk: true,
    identifiedDate: "2026-01-12",
    reviewDate: "2026-09-30",
    status: "Đang theo dõi",
    statusNote: "",
    estimatedLoss: 2400000000,
    tags: ["hạ tầng", "sẵn sàng"],
  },
  {
    ...seedBase("risk-02", "RISK-2026-002"),
    name: "Rò rỉ dữ liệu khách hàng qua kênh đối tác",
    description:
      "Đối tác đại lý truy cập dữ liệu khách hàng vượt phạm vi được cấp quyền.",
    cause:
      "Phân quyền chưa theo nguyên tắc tối thiểu, thiếu giám sát nhật ký truy cập.",
    consequence:
      "Vi phạm quy định bảo vệ dữ liệu cá nhân, bị xử phạt và tổn hại uy tín thương hiệu.",
    categoryId: "cat-attt",
    objectiveIds: ["obj-05", "obj-08"],
    unitId: "unit-it",
    ownerId: "emp-tuan",
    processId: "prc-attt",
    systemId: "sys-crm",
    source: "Kết hợp",
    inherentLikelihood: 4,
    inherentImpact: 5,
    residualLikelihood: 2,
    residualImpact: 5,
    treatment: "Giảm thiểu",
    treatmentNote:
      "Rà soát ma trận phân quyền theo vai trò, bật nhật ký truy cập và cảnh báo bất thường.",
    isZeroTolerance: true,
    isKeyRisk: true,
    identifiedDate: "2026-01-20",
    reviewDate: "2026-08-31",
    status: "Đang xử lý",
    statusNote: "",
    estimatedLoss: 3200000000,
    tags: ["bảo mật", "dữ liệu cá nhân"],
  },
  {
    ...seedBase("risk-03", "RISK-2026-003"),
    name: "Nợ phải thu quá hạn tăng cao",
    description:
      "Công nợ khách hàng doanh nghiệp quá hạn trên 90 ngày tăng nhanh trong 2 quý liên tiếp.",
    cause: "Chính sách bán chịu nới lỏng, thiếu đánh giá tín dụng đầu vào.",
    consequence:
      "Dòng tiền suy giảm, tăng chi phí vốn và chi phí trích lập dự phòng.",
    categoryId: "cat-tc",
    objectiveIds: ["obj-06", "obj-01"],
    unitId: "unit-tc",
    ownerId: "emp-mai",
    processId: "prc-ban",
    systemId: "sys-erp",
    source: "Bên ngoài",
    inherentLikelihood: 4,
    inherentImpact: 4,
    residualLikelihood: 3,
    residualImpact: 3,
    treatment: "Giảm thiểu",
    treatmentNote:
      "Siết hạn mức tín dụng, chấm điểm khách hàng bắt buộc trước khi ký hợp đồng.",
    isZeroTolerance: false,
    isKeyRisk: true,
    identifiedDate: "2026-01-15",
    reviewDate: "2026-10-15",
    status: "Đang theo dõi",
    statusNote: "",
    estimatedLoss: 1800000000,
    tags: ["công nợ", "dòng tiền"],
  },
  {
    ...seedBase("risk-04", "RISK-2026-004"),
    name: "Chậm tiến độ phát hành sản phẩm chủ lực",
    description:
      "Sản phẩm mới không kịp ra mắt theo cam kết với thị trường và khách hàng lớn.",
    cause: "Yêu cầu thay đổi liên tục giữa chu kỳ, thiếu nguồn lực kiểm thử.",
    consequence: "Mất cơ hội thị trường, giảm doanh thu so với kế hoạch năm.",
    categoryId: "cat-cl",
    objectiveIds: ["obj-03", "obj-01"],
    unitId: "unit-sx",
    ownerId: "emp-binh",
    processId: "prc-pt",
    systemId: "",
    source: "Nội bộ",
    inherentLikelihood: 4,
    inherentImpact: 4,
    residualLikelihood: 3,
    residualImpact: 3,
    treatment: "Giảm thiểu",
    treatmentNote:
      "Chốt phạm vi theo từng phiên bản, bổ sung nhân sự và mở rộng kiểm thử tự động.",
    isZeroTolerance: false,
    isKeyRisk: false,
    identifiedDate: "2026-02-02",
    reviewDate: "2026-09-01",
    status: "Đang theo dõi",
    statusNote: "",
    estimatedLoss: 900000000,
    tags: ["tiến độ", "sản phẩm"],
  },
  {
    ...seedBase("risk-05", "RISK-2026-005"),
    name: "Mất nhân sự chủ chốt mảng kỹ thuật",
    description:
      "Nhân sự nắm giữ tri thức lõi nghỉ việc khi chưa có người kế thừa được đào tạo.",
    cause:
      "Chưa xây dựng lộ trình kế thừa và chưa tài liệu hoá tri thức hệ thống.",
    consequence:
      "Gián đoạn phát triển, tăng chi phí tuyển dụng và đào tạo lại.",
    categoryId: "cat-ns",
    objectiveIds: ["obj-07", "obj-03"],
    unitId: "unit-ns",
    ownerId: "emp-anh",
    processId: "prc-ns",
    systemId: "sys-hr",
    source: "Nội bộ",
    inherentLikelihood: 3,
    inherentImpact: 4,
    residualLikelihood: 3,
    residualImpact: 3,
    treatment: "Giảm thiểu",
    treatmentNote:
      "Xây dựng bản đồ vị trí trọng yếu, chương trình kế thừa và cơ chế giữ chân.",
    isZeroTolerance: false,
    isKeyRisk: false,
    identifiedDate: "2026-02-05",
    reviewDate: "",
    status: "Đã duyệt",
    statusNote: "",
    estimatedLoss: 600000000,
    tags: ["nhân sự", "kế thừa"],
  },
  {
    ...seedBase("risk-06", "RISK-2026-006"),
    name: "Vi phạm quy định bảo vệ dữ liệu cá nhân",
    description:
      "Hoạt động thu thập và xử lý dữ liệu cá nhân chưa đáp ứng đủ yêu cầu pháp lý hiện hành.",
    cause:
      "Chưa rà soát toàn bộ điểm thu thập dữ liệu và cơ sở pháp lý của việc xử lý.",
    consequence:
      "Bị xử phạt hành chính, buộc dừng một số hoạt động xử lý dữ liệu đang vận hành.",
    categoryId: "cat-tt",
    objectiveIds: ["obj-08"],
    unitId: "unit-qtrr",
    ownerId: "emp-ha",
    processId: "prc-attt",
    systemId: "sys-crm",
    source: "Bên ngoài",
    inherentLikelihood: 3,
    inherentImpact: 5,
    residualLikelihood: 2,
    residualImpact: 4,
    treatment: "Giảm thiểu",
    treatmentNote:
      "Lập danh mục hoạt động xử lý dữ liệu và hồ sơ đánh giá tác động theo quy định.",
    isZeroTolerance: true,
    isKeyRisk: true,
    identifiedDate: "2026-01-25",
    reviewDate: "2026-11-30",
    status: "Đang theo dõi",
    statusNote: "",
    estimatedLoss: 1500000000,
    tags: ["tuân thủ", "dữ liệu cá nhân"],
  },
  {
    ...seedBase("risk-07", "RISK-2026-007"),
    name: "Sai sót trong quy trình mua hàng và thanh toán",
    description:
      "Thanh toán trùng hoặc thanh toán sai đối tượng thụ hưởng trong chu trình mua hàng.",
    cause:
      "Chưa đối chiếu tự động giữa đơn mua, phiếu nhập và hoá đơn nhà cung cấp.",
    consequence:
      "Thất thoát tài chính, khó thu hồi và ảnh hưởng báo cáo tài chính.",
    categoryId: "cat-tc",
    objectiveIds: ["obj-06"],
    unitId: "unit-tc",
    ownerId: "emp-mai",
    processId: "prc-mua",
    systemId: "sys-erp",
    source: "Nội bộ",
    inherentLikelihood: 3,
    inherentImpact: 4,
    residualLikelihood: 2,
    residualImpact: 3,
    treatment: "Giảm thiểu",
    treatmentNote:
      "Bật đối chiếu ba chiều tự động trên ERP và phân tách nhiệm vụ lập - duyệt - chi.",
    isZeroTolerance: false,
    isKeyRisk: false,
    identifiedDate: "2026-02-08",
    reviewDate: "2026-10-31",
    status: "Đang theo dõi",
    statusNote: "",
    estimatedLoss: 750000000,
    tags: ["mua hàng", "gian lận"],
  },
  {
    ...seedBase("risk-08", "RISK-2026-008"),
    name: "Phụ thuộc nhà cung cấp dịch vụ đám mây duy nhất",
    description:
      "Toàn bộ dịch vụ khách hàng đặt trên một nhà cung cấp đám mây, không có phương án thay thế.",
    cause: "Kiến trúc triển khai gắn chặt với dịch vụ riêng của nhà cung cấp.",
    consequence:
      "Khi nhà cung cấp gián đoạn hoặc tăng giá đột biến, doanh nghiệp không có lựa chọn thay thế.",
    categoryId: "cat-cntt",
    objectiveIds: ["obj-04"],
    unitId: "unit-it",
    ownerId: "emp-tuan",
    processId: "prc-van-hanh",
    systemId: "sys-cloud",
    source: "Bên ngoài",
    inherentLikelihood: 3,
    inherentImpact: 4,
    residualLikelihood: 3,
    residualImpact: 4,
    treatment: "Chuyển giao",
    treatmentNote:
      "Đàm phán cam kết mức dịch vụ kèm bồi thường, mua bảo hiểm gián đoạn kinh doanh.",
    isZeroTolerance: false,
    isKeyRisk: false,
    identifiedDate: "2026-02-12",
    reviewDate: "",
    status: "Chờ duyệt",
    statusNote: "",
    estimatedLoss: 1100000000,
    tags: ["bên thứ ba", "đám mây"],
  },
  {
    ...seedBase("risk-09", "RISK-2026-009"),
    name: "Suy giảm tỷ lệ gia hạn do chất lượng hỗ trợ",
    description:
      "Khách hàng không gia hạn dịch vụ vì thời gian phản hồi hỗ trợ kéo dài.",
    cause: "Số lượng yêu cầu tăng nhanh, quy trình phân luồng chưa tối ưu.",
    consequence:
      "Doanh thu định kỳ suy giảm, chi phí tìm khách hàng mới tăng.",
    categoryId: "cat-vh",
    objectiveIds: ["obj-02", "obj-01"],
    unitId: "unit-kd",
    ownerId: "emp-son",
    processId: "prc-ban",
    systemId: "sys-crm",
    source: "Kết hợp",
    inherentLikelihood: 3,
    inherentImpact: 3,
    residualLikelihood: 2,
    residualImpact: 3,
    treatment: "Giảm thiểu",
    treatmentNote:
      "Chuẩn hoá cam kết thời gian phản hồi theo hạng khách hàng, bổ sung nhân sự hỗ trợ.",
    isZeroTolerance: false,
    isKeyRisk: false,
    identifiedDate: "2026-02-15",
    reviewDate: "",
    status: "Nháp",
    statusNote: "",
    estimatedLoss: 500000000,
    tags: ["khách hàng", "dịch vụ"],
  },
  {
    ...seedBase("risk-10", "RISK-2026-010"),
    name: "Biến động tỷ giá ảnh hưởng chi phí hạ tầng",
    description:
      "Chi phí thuê hạ tầng nước ngoài thanh toán bằng ngoại tệ biến động theo tỷ giá.",
    cause: "Hợp đồng dài hạn niêm yết bằng ngoại tệ, chưa có công cụ phòng vệ.",
    consequence: "Chi phí vận hành vượt ngân sách được duyệt.",
    categoryId: "cat-tc",
    objectiveIds: ["obj-06"],
    unitId: "unit-tc",
    ownerId: "emp-mai",
    processId: "prc-mua",
    systemId: "sys-erp",
    source: "Bên ngoài",
    inherentLikelihood: 3,
    inherentImpact: 2,
    residualLikelihood: 2,
    residualImpact: 2,
    treatment: "Chấp nhận",
    treatmentNote: "",
    isZeroTolerance: false,
    isKeyRisk: false,
    identifiedDate: "2026-01-30",
    reviewDate: "2026-12-31",
    status: "Đã đóng",
    statusNote: "Mức rủi ro còn lại nằm trong khẩu vị rủi ro đã phê duyệt.",
    estimatedLoss: 320000000,
    tags: ["tỷ giá"],
  },
];
